	import { roomTypeBean } from "@/bean/roomTypeBean.uts";
	import i18n from '@/i18n/index.uts';
export const  validRoomTypeForm = (roomTypeForm:roomTypeBean):boolean=>{
	let msg ="";
	if(roomTypeForm.name==""){
		//msg="请填写房型名称";
		msg=i18n.global.t("hotel.form.valid_room_type_name")
		
	}
	if(roomTypeForm.bedList.length<1){
		//msg="请选择床位";
		msg=i18n.global.t("hotel.form.valid_room_type_bed")
	
	}
	if(roomTypeForm.guestNumber<1){
		//msg="入住人数最少1人";
		msg=i18n.global.t("hotel.form.valid_room_type_guestNumber")
	
	}
	if(roomTypeForm.priceBase<1){
		//msg="房型价格不得低于1元";
		msg=i18n.global.t("hotel.form.valid_room_type_priceBase")
	}
	if(msg!=""){
		uni.showToast({
			title:msg,
			icon:"none"
		})
		return false;
	}
	return true;
}