import {FMService} from '@/services/FMService';
import { FMBean,FMTypeConfigBean } from '@/bean/FMBean';
export type FmState = {
	incomeAndExpensesConfig:Array<FMTypeConfigBean>,
	fmList : Array<FMBean>,//今天及以后的订单
}

//实例化
export const fmState = reactive({
	incomeAndExpensesConfig:[],
	fmList: [] as Array<FMBean>,//今天及以后的订单

} as FmState)

export const setIncomeAndExpensesConfig = (list : Array<FMTypeConfigBean>) => {
	fmState.incomeAndExpensesConfig = list;
}
export const updateFmList = (list : Array<FMBean>) => {
	fmState.fmList = list;
}
