import { DB } from '../api/DB';
import { callFunctionRes } from "@/bean/DBBean";
import { userBean } from '@/bean/userBean';
import { showDialog, hideDialog } from "@/uni_modules/rice-ui";
import { setToken } from "@/store/store.uts";
import {action_co,RequestFailModal} from "@/api/cloudApi.uts";

class AccountServiceClass {

	constructor() {
		
	}
	/**
	 * 发送短信验证吗
	 */
	async sendSmsCode(phone : string) : Promise<string> {
		//const data : UTSJSONObject = { phone };
	//	return DB.callFunction("hm-sendSms", data);
	try {
		const res = await action_co.user_sendSms(phone);
		const data = res['data'] as UTSJSONObject;
		const tk = data.getString("tk")??"";
		return tk;
	} catch (error:Error) {
		RequestFailModal(error.message);
		throw new Error(error.message)
	}
		
	}
	//腾讯地图 web secret =   qvQRgL3QqGosrlh7BrIyleFrs3Phs0X9
	// getConfig() : Promise<UniCloudCallFunctionResult<UTSJSONObject>> {
	// 	//  const data:UTSJSONObject={"a":1};
	// 	return DB.callFunction("hm_getConfig");
	// }
	async validToken(token:string) : Promise<boolean> {
		try {			
			const res = await action_co.user_validToken(token);
			const flag = res['data'] as boolean;
			return flag;
		} catch (error:Error) {
			console.log(error)
			RequestFailModal(error.message);
			throw new Error("valid token fail");
			//return false;
		}
		
	}
	async sendEmailCode(email : string,type:string):Promise<string> {
		try {
			const res = await action_co.sendEmailCode(email,type);
			console.log("send email code", res);
			const data = res['data'] as UTSJSONObject;
			const emailCodeTk = data.getString("emailCodeTk")??"";
			return emailCodeTk;
		} catch (error:Error) {
			throw new Error(error.message as string)
		}
	}
	/**
	 * 注册账号验证是否存在
	 */

	async validRegisterAccount(account : string) : Promise<boolean> {
		if (account == "") {
			throw new Error("账号不能为空")
		}
		try {
			const params = { account } as UTSJSONObject;
			const res = await DB.getCollection("hm-user", params);
			const data = res['data'] as Array<UTSJSONObject>;
			const flag = data.length > 0;
			return flag;
		} catch (error::Error) {
			throw new Error("系统异常");
		}

	}
	async validRegisterByEmail(email : string) : Promise<boolean> {
		let flag = false;
		if (email == "") {
			throw new Error("邮箱不能为空");
		}
		try {
			const params = { email } as UTSJSONObject;
			const res = await DB.getCollection("hm-user", params);
			const data = res['data'] as Array<UTSJSONObject>;
			if( data.length <1){
				flag=true;
			}
			return flag;
		} catch (error::Error) {
			throw new Error("system error");			
		}
		
	}
	//验证邮箱与验证码
	async validEmailAndCode(email : string,emailCode:string,emailCodeTk:string):Promise<boolean>{
		try {
			//await account_co.validEmailAndCode(email,emailCode,emailCodeTk);
			const res =	await action_co.user_validEmailAndCode(email,emailCode,emailCodeTk);
			const data = res['data'] as boolean;
			return data;
		} catch (error:Error) {
			//return false;
			console.log("eeee",error)
			throw new Error(error.message as string);
		}
	}
	async register(user : UTSJSONObject) : Promise<boolean> {
		console.log("user---", user)
		try {
			await action_co.user_register(user);
			return true
		} catch (error:Error) {
			return false;
		}
	}
	async LoginByAccount(userForm:UTSJSONObject): Promise<boolean>{
		try {
			//const res = await account_co.login(userForm);
			const res = await action_co.user_loginByAccountAndPassword(userForm);
			const data = res['data'] as UTSJSONObject;	
			const token = data.getString("token") ?? ""
			if (token != "") {
				setToken(token);
				uni.setStorageSync("hm_token", token as string);
				uni.setStorageSync("uniIdToken", token as string);				
			}
			return true;
		} catch (error:Error) {
			console.error(error)
			RequestFailModal(error.message);
			//throw new Error(error.message as string);
			return false;
		}
	}
	async LoginBySms(userForm:UTSJSONObject): Promise<boolean>{
		try {
			//const res = await account_co.login(userForm);
			const res = await action_co.user_loginBySmsCode(userForm);
			console.log("login=====",res);
			const data = res['data'] as UTSJSONObject;	
			const token = data.getString("token") ?? ""
			if (token != "") {
				setToken(token);
				uni.setStorageSync("hm_token", token as string);
				uni.setStorageSync("uniIdToken", token as string);
			}
			return true;
		} catch (error:Error) {
			console.log(error.message)
			RequestFailModal(error.message);
			throw new Error(error.message as string);
		}
	}
	async LoginByAPP(userForm:UTSJSONObject): Promise<boolean>{
		try {
			//const res = await account_co.login(userForm);
			const res = await action_co.user_loginByApp(userForm);
			const data = res['data'] as UTSJSONObject;	
			const token = data.getString("token") ?? ""
			if (token != "") {
				setToken(token);
				uni.setStorageSync("hm_token", token as string);
				uni.setStorageSync("uniIdToken", token as string);
			}
			return true;
		} catch (error:Error) {
			console.error(error)
			RequestFailModal(error.message);
			//throw new Error(error.message as string);
			return false;
		}
	}
	
	/**
	 * 更新密码
	 */
	async updatePassword(password:string,originPassword:string):Promise<boolean>{
		try {
			//const token = uni.getStorageSync("hm_token");
			//await account_co.updatePassword(token,password,originPassword);
			await action_co.user_updatePassword(password,originPassword);
			return true;
		} catch (error:Error) {
			console.log("1eeeeeeee",error);
			RequestFailModal(error.message);
			//throw new Error(error.message as string);
			return false;
			
		}
	}
	async resetPasswordByEmail(email:string,emailCode:string, emailCodeTk:string, password:string):Promise<boolean>{
		try {
			await action_co.user_resetPasswordByEmailCode(email,emailCode, emailCodeTk, password);
			return true;
		} catch (error:Error) {
			RequestFailModal(error.message)
			throw new Error(error.message as string)
		}
	}
	/**
	 * 注销账号
	 */
	async closeAccount() : Promise<boolean> {
		try {
			//const res = await DB.callFunction("hm_closeAccount");
			await action_co.user_closeAccount();
			return true;
		} catch (error:Error) {
			throw new Error("账号注销失败")
		}

	}
	recoverAccount(_id : string) : Promise<UniCloudDBUpdateResult> {
		return DB.update("hm-user", _id, { accountStatus: 1 })
	}
	async getUserInfoByPhone(phone : string) : Promise<userBean | null> {
		const res = await DB.getCollection("hm-user", { phone } as UTSJSONObject);
		const list = res['data'] as Array<UTSJSONObject>;
		let user : userBean | null = null;
		if (list != null && list.length > 0) {
			const userObj = list[0];
			user = {
				_id: userObj.getString("_id") ?? "",
				idCard: userObj.getString("idCard") ?? "",
				ipStartDateStamp: userObj.getString("ipStartDateStamp") ?? "",
				isVip: userObj.getBoolean("isVip") ?? false,
				nickName: userObj.getString("nickName") ?? "",
				phone: userObj.getString("phone") ?? "",
				email: userObj.getString("email") ?? "",
				account: userObj.getString("account") ?? "",
				userId: userObj.getString("userId") ?? "",
				userName: userObj.getString("userName") ?? "",
				vipEndDate: userObj.getString("vipEndDate") ?? "",
				vipEndDateStamp: userObj.getString("vipEndDateStamp") ?? "",
				closeAccountDateTime: userObj.getNumber("closeAccountDateTime") ?? null,
				vipStartDate: userObj.getString("vipStartDate") ?? "",
				wxNickName: userObj.getString("wxNickName") ?? "",
				wxOpenId: userObj.getString("wxOpenId") ?? "",
				hm_token: userObj.getString("hm_token") ?? "",
				avatar: userObj.getString("avatar") ?? "",
				accountStatus: userObj.getNumber("accountStatus") ?? 1
			}

		}
		return user;
	}
	async getuserByToken() : Promise<userBean | null> {
		//const res = await DB.callFunction("hm_getUser", { type: 'token', value: uni.getStorageSync("hm_token") });
		try{
			const res = await action_co.user_getUser();
			console.log("222222",res);
			const data = res['data'] as Array<UTSJSONObject>;
			if(data.length<1){
				throw new Error("dont valid user");
			}
			const userObj = data[0] as UTSJSONObject;
			let user : userBean | null = null;
			user = {
				_id: userObj.getString("_id") ?? "",
				idCard: userObj.getString("idCard") ?? "",
				ipStartDateStamp: userObj.getString("ipStartDateStamp") ?? "",
				isVip: userObj.getBoolean("isVip") ?? false,
				nickName: userObj.getString("nickName") ?? "",
				phone: userObj.getString("phone") ?? "",
				email: userObj.getString("email") ?? "",
				userId: userObj.getString("userId") ?? "",
				userName: userObj.getString("userName") ?? "",
				vipEndDate: userObj.getString("vipEndDate") ?? "",
				vipEndDateStamp: userObj.getString("vipEndDateStamp") ?? "",
				closeAccountDateTime: userObj.getNumber("closeAccountDateTime") ?? null,
				vipStartDate: userObj.getString("vipStartDate") ?? "",
				wxNickName: userObj.getString("wxNickName") ?? "",
				wxOpenId: userObj.getString("wxOpenId") ?? "",
				hm_token: userObj.getString("hm_token") ?? "",
				avatar: userObj.getString("avatar") ?? "",
				account: userObj.getString("account") ?? "",
				accountStatus: userObj.getNumber("accountStatus") ?? 1
			}
			
			//}
			return user;
		}catch(error:Error){
			RequestFailModal(error.message);
			throw error;
		}
		
	}
	async updateUser(_id : string, userObj : UTSJSONObject) : Promise<boolean> {
		try {
			await DB.update("hm-user", _id, userObj);
			return true;
		} catch (error:Error) {
			throw new Error("更新失败");
		}

	}
	updateUserName(_id : string, userName : string) : Promise<UniCloudDBUpdateResult> {
		return DB.update("hm-user", _id, { userName } as UTSJSONObject);
	}
	getRechargeConfig() : Promise<UniCloudDBGetResult> {
		return DB.getCollection("hm-rechargeConfig", { status: true });
	}
	createRechargeOrder(rechargeConfig_id : string) : Promise<UniCloudCallFunctionResult<UTSJSONObject>> {
		return DB.callFunction("hm_createRechargeOrder", { rechargeConfig_id });
	}

	getMpPhoneNumber(code : string) : Promise<UniCloudCallFunctionResult<UTSJSONObject>> {
		return DB.callFunction("getMpPhoneNumber", { code } as UTSJSONObject);
	}
	loginMp(code : string) : Promise<UniCloudCallFunctionResult<UTSJSONObject>> {
		return DB.callFunction("hm_loginMp", { code } as UTSJSONObject);
	}
}
//module.exports =new AccountService();
export var AccountService = new AccountServiceClass();