import { DB } from '../api/DB';
import { callFunctionRes } from "@/bean/DBBean";
import { userBean } from '@/bean/userBean';
import { showDialog, hideDialog } from "@/uni_modules/rice-ui";
import { ActionService } from './ActionService';

const se_co = uniCloud.importObject("send_email_co");
const account_co = uniCloud.importObject("hm_account_co");

class AccountServiceClass {
	constructor() {}

	sendSmsCode(phone : string) : Promise<UniCloudCallFunctionResult<UTSJSONObject>> {
		return ActionService.user_sendSms(phone);
	}
	getConfig() : Promise<UniCloudCallFunctionResult<UTSJSONObject>> {
		return ActionService.config_getConfig();
	}
	validToken() : Promise<UniCloudCallFunctionResult<UTSJSONObject>> {
		return ActionService.user_validToken();
	}
	async sendEmailCode(email : string, type:string): Promise<string> {
		try {
			const res = await se_co.sendEmailCode(email, type);
			console.log("send email code", res);
			const data = res['data'] as UTSJSONObject;
			const emailCodeTk = data.getString("emailCodeTk") ?? "";
			return emailCodeTk;
		} catch (error) {
			throw new Error(error.message as string)
		}
	}
	async validRegisterAccount(account : string) : Promise<boolean> {
		console.log("aacc", account);
		if (account == "") {
			throw new Error("账号不能为空")
		}
		try {
			const params = { account } as UTSJSONObject;
			const res = await DB.getCollection("hm-user", params);
			const data = res['data'] as Array<UTSJSONObject>;
			const flag = data.length > 0;
			return flag;
		} catch (e) {
			throw new Error("系统异常");
		}
	}
	async validRegisterByEmail(email : string) : Promise<boolean> {
		console.log("aacc", email);
		let flag = false;
		if (email == "") {
			throw new Error("邮箱不能为空");
		}
		try {
			const params = { email } as UTSJSONObject;
			const res = await DB.getCollection("hm-user", params);
			const data = res['data'] as Array<UTSJSONObject>;
			if( data.length < 1){
				flag = true;
			}
			return flag;
		} catch (e) {
			throw new Error("系统异常");
		}
	}
	async validEmailAndCode(email : string, emailCode:string, emailCodeTk:string): Promise<boolean> {
		try {
			await account_co.validEmailAndCode(email, emailCode, emailCodeTk);
			return true;
		} catch (error) {
			console.log("eeee", error)
			throw new Error(error.message as string);
		}
	}
	async register(user : UTSJSONObject) : Promise<boolean> {
		console.log("user---", user)
		try {
			await account_co.register(user);
			return true
		} catch (error) {
			console.log("aaaaaaaaa", error);
			return false;
		}
	}
	async Login(userForm:UTSJSONObject): Promise<boolean> {
		try {
			const res = await account_co.login(userForm);
			const data = res['data'] as UTSJSONObject;	
			const token = data.getString("token") ?? ""
			if (token != "") {
				uni.setStorageSync("hm_token", token as string);
			}
			return true;
		} catch (error) {
			console.error(error)
			throw new Error(error.message as string);
		}
	}
	async login(userForm : UTSJSONObject) : Promise<boolean> {
		try {
			const res = await ActionService.user_login(userForm);
			const result = res['result'] as UTSJSONObject;
			if (result.getNumber("errCode") != 0) {
				throw new Error(result.getString("errMsg") ?? "系统异常");
			}
			const data = result.getJSON("data") ?? {}
			const token = data.getString("token") ?? ""
			if (token != "") {
				uni.setStorageSync("hm_token", token as string);
			}
			return true;
		} catch (err) {
			uni.showToast({
				title: err.message as string,
				icon: "none"
			})
			throw new Error(err.message.toString());
		}
	}
	async updatePassword(password:string, originPassword:string): Promise<boolean> {
		try {
			const token = uni.getStorageSync("hm_token");
			await account_co.updatePassword(token, password, originPassword);
			return true;
		} catch (error) {
			console.log("1eeeeeeee", error);
			throw new Error(error.message as string);
		}
	}
	async resetPasswordByEmail(email:string, emailCode:string, emailCodeTk:string, password:string): Promise<boolean> {
		try {
			await account_co.resetPasswordByEmailCode(email, emailCode, emailCodeTk, password);
			return true;
		} catch (error) {
			throw new Error(error.message as string)
		}
	}
	async closeAccount() : Promise<boolean> {
		try {
			await ActionService.user_closeAccount();
			console.log("11111注销账号")
			return true;
		} catch (error) {
			throw new Error("账号注销失败")
		}
	}
	recoverAccount(_id : string) : Promise<UniCloudDBUpdateResult> {
		return DB.update("hm-user", _id, { accountStatus: 1 })
	}
	async getUserInfoByPhone(phone : string) : Promise<userBean | null> {
		const res = await DB.getCollection("hm-user", { phone } as UTSJSONObject);
		const list = res['data'] as Array<UTSJSONObject>;
		let user : userBean | null = null;
		if (list != null && list.length > 0) {
			const userObj = list[0];
			user = {
				_id: userObj.getString("_id") ?? "",
				idCard: userObj.getString("idCard") ?? "",
				ipStartDateStamp: userObj.getString("ipStartDateStamp") ?? "",
				isVip: userObj.getBoolean("isVip") ?? false,
				nickName: userObj.getString("nickName") ?? "",
				phone: userObj.getString("phone") ?? "",
				email: userObj.getString("email") ?? "",
				account: userObj.getString("account") ?? "",
				userId: userObj.getString("userId") ?? "",
				userName: userObj.getString("userName") ?? "",
				vipEndDate: userObj.getString("vipEndDate") ?? "",
				vipEndDateStamp: userObj.getString("vipEndDateStamp") ?? "",
				closeAccountDateTime: userObj.getNumber("closeAccountDateTime") ?? null,
				vipStartDate: userObj.getString("vipStartDate") ?? "",
				wxNickName: userObj.getString("wxNickName") ?? "",
				wxOpenId: userObj.getString("wxOpenId") ?? "",
				hm_token: userObj.getString("hm_token") ?? "",
				avatar: userObj.getString("avatar") ?? "",
				accountStatus: userObj.getNumber("accountStatus") ?? 1
			}
		}
		return user;
	}
	async getuserByToken() : Promise<userBean | null> {
		const res = await ActionService.user_getUser('token', uni.getStorageSync("hm_token"));
		console.log("user:::",res);
		const data = res["data"] as UTSJSONObject[];
		const userObj = data[0];
		let user : userBean | null = null;
		user = {
			_id: userObj.getString("_id") ?? "",
			idCard: userObj.getString("idCard") ?? "",
			ipStartDateStamp: userObj.getString("ipStartDateStamp") ?? "",
			isVip: userObj.getBoolean("isVip") ?? false,
			nickName: userObj.getString("nickName") ?? "",
			phone: userObj.getString("phone") ?? "",
			email: userObj.getString("email") ?? "",
			userId: userObj.getString("userId") ?? "",
			userName: userObj.getString("userName") ?? "",
			vipEndDate: userObj.getString("vipEndDate") ?? "",
			vipEndDateStamp: userObj.getString("vipEndDateStamp") ?? "",
			closeAccountDateTime: userObj.getNumber("closeAccountDateTime") ?? null,
			vipStartDate: userObj.getString("vipStartDate") ?? "",
			wxNickName: userObj.getString("wxNickName") ?? "",
			wxOpenId: userObj.getString("wxOpenId") ?? "",
			hm_token: userObj.getString("hm_token") ?? "",
			avatar: userObj.getString("avatar") ?? "",
			account: userObj.getString("account") ?? "",
			accountStatus: userObj.getNumber("accountStatus") ?? 1
		}
		return user;
	}
	async updateUser(_id : string, userObj : UTSJSONObject) : Promise<boolean> {
		try {
			await DB.update("hm-user", _id, userObj);
			return true;
		} catch (e) {
			throw new Error("更新失败");
		}
	}
	updateUserName(_id : string, userName : string) : Promise<UniCloudDBUpdateResult> {
		return DB.update("hm-user", _id, { userName } as UTSJSONObject);
	}
	getRechargeConfig() : Promise<UniCloudDBGetResult> {
		return DB.getCollection("hm-rechargeConfig", { status: true });
	}
	createRechargeOrder(rechargeConfig_id : string) : Promise<UniCloudCallFunctionResult<UTSJSONObject>> {
		return ActionService.fm_createRechargeOrder(rechargeConfig_id);
	}
	getMpPhoneNumber(code : string) : Promise<UniCloudCallFunctionResult<UTSJSONObject>> {
		return DB.callFunction("getMpPhoneNumber", { code } as UTSJSONObject);
	}
	loginMp(code : string) : Promise<UniCloudCallFunctionResult<UTSJSONObject>> {
		return ActionService.user_loginMp(code);
	}
}
export var AccountService = new AccountServiceClass();