import { DB,dbJQL } from '../api/DB';
import { FMBean, FMTypeConfigBean, FMDataListResult } from '@/bean/FMBean';
import { dayuts } from '@/uni_modules/lime-dayuts';
import { TIME, MOONTH_START_END_TIMESTAMP, getMonthFirstDay, getMonthLastDay } from "@/static/utils/TIME";
import { fmState } from "@/store/modules/fmStore.uts";
import { charPietItem } from "@/bean/chartBean.uts";
import {action_co,getTokenObject,RequestFailModal} from "@/api/cloudApi.uts";
class FMServiceClass {
	constructor() {
		// this.DB=DB;
		//  this.validTokenRequest=null;
	}
	async getIncomeAndExpensesConfig() : Promise<Array<FMTypeConfigBean>> {
		const db =dbJQL;
		const dbCmd = db.command;
		try {
			const w = {
				billType: dbCmd.or([dbCmd.eq("income"), dbCmd.eq("expenses")])
			}
			const res = await db.collection("hm-incomeAndExpensesConfig").where(w).orderBy("name asc").get();
			const data = res['data'] as Array<UTSJSONObject>;
			let list : Array<FMTypeConfigBean> = [];
			data.forEach(item => {
				const obj : FMTypeConfigBean = {
					_id: item.getString("_id") ?? "",
					billType: item.getString("billType") ?? "",
					name: item.getString("name") ?? "",
					text: item.getString("text") ?? ""
				}
				list.push(obj);
			})
			return list;
		} catch (error) {
			//TODO handle the exception
			throw new Error("获取收支配置失败");
		}
	}
	async add(item : FMBean) : Promise<boolean> {
		const fm = {
			amount: parseFloat(item.amount.toString()),
			billType: item.billType,
			creater: item.creater,
			hotel_id: item.hotel_id,
			ioeTime: item.ioeTime,
			type: item.type,
			mark: item.mark
		}
		try {
			// const res = await DB.add("hm-incomeAndExpenses", fm);
			// const id = res['id'] as string;
			// if (id == "") {
			// 	uni.showToast({
			// 		title: "添加异常",
			// 		icon: "none"
			// 	});
			// 	throw new Error("添加失败");
			// }
			// uni.showToast({
			// 	title: "添加成功",
			// 	icon: "none"
			// });
			// return true;
			const res = await action_co.fm_add(fm);
			const id = res['id'] as string;
			console.log("add order",res);
			return id!="";
		} catch (error) {
			throw new Error("添加收支失败");
		}

	}
	async edit(item : FMBean) : Promise<boolean> {
		const _id = item._id;
		const fm = {
			amount: parseFloat(item.amount.toString()),
			billType: item.billType,
			creater: item.creater,
			hotel_id: item.hotel_id,
			ioeTime: item.ioeTime,
			type: item.type,
			mark: item.mark
		}
		try {
			await DB.update("hm-incomeAndExpenses", _id, fm);
			uni.showToast({
				title: "更新成功",
				icon: "none"
			});
			return true;
		} catch (error) {
			throw new Error("更新收支失败");
		}

	}
	async deleteFm(fm_id : string):Promise<boolean> {
		try {
			// const res = await DB.callFunction("hm_deleteFm", {
			// 	_id: fm_id,
			// });
			await action_co.fm_deleteFm(fm_id);
			return true;
		} catch (error:Error) {
			RequestFailModal(error.message);
			//throw new Error("删除失败");
			return false;

		}

	}
	async getFmById(fm_id : string):Promise<FMBean>{
		const w = {
			_id:fm_id
		}
		try {
			const res = await DB.getCollection("hm-incomeAndExpenses",w);
			const data = res['data'] as Array<UTSJSONObject>;
			if(data.length>0){
				const item = data[0]
				const fm:FMBean={
					_id: item.getString("_id") ?? "",
					amount: item.getNumber("amount") ?? 0,
					billType: item.getString("billType") ?? "",
					createTime: item.getNumber("createTime") ?? 0,
					creater: item.getString("creater") ?? "",
					//data_status: item.getNumber("data_status") ?? 0,
					hotel_id: item.getString("hotel_id") ?? "",
					ioeTime: item.getNumber("ioeTime") ?? 0,
					mark: item.getString("mark") ?? "",
					type: item.getString("type") ?? "",
					unit: item.getString("unit") ?? ""
				}
				console.log("getfm",fm)
				 return fm;
			}else{
				throw new Error("not find data");
			}
		
			
		} catch (error) {
			throw new Error("get data fail");
		
		}
	}

	//获取收入与支出分类
	async getIncomeAndExpensesDateBySearch(hotel_id : string, billType : string, keyword : string, dateRange : string[], pageNo : number, pageSize : number) : Promise<FMDataListResult> {
		const db = dbJQL;
		const dbCmd = db.command;
		let st : number = TIME.getCurrentMonthFirst(new Date());
		let et : number = TIME.getCurrentMonthLast(new Date());
		if (dateRange != null && dateRange.length == 2) {
			st = TIME.startTime(new Date(dateRange[0]));
			et = TIME.endTime(new Date(dateRange[1]));
		}
		const w = {
			hotel_id: hotel_id,
			mark: new RegExp(`${keyword}`),
			billType: billType == 'all' ? dbCmd.neq('') : billType,
			ioeTime: dbCmd.and([dbCmd.gte(st), dbCmd.lte(et)])
		}
		let FMList : Array<FMBean> = [];
		let skipnum : number = Math.max((pageNo - 1) * pageSize, 0);
		//const main = db.collection("hm-incomeAndExpenses").where(w).orderBy("ioeTime desc").skip(skipnum).limit(pageSize).getTemp();
		//const config = db.collection("hm-incomeAndExpensesConfig").getTemp();
		console.log(new Date().getTime());
		try {
			//const res = await db.collection(main).get({ getCount: true });
			const res = await db.collection("hm-incomeAndExpenses").where(w).orderBy("ioeTime desc").skip(skipnum).limit(pageSize).get({ getCount: true });
			console.log(new Date().getTime());
			console.log("res", res);
			const data = res['data'] as Array<UTSJSONObject>;

			if (data != null) {
				data.forEach((item : UTSJSONObject) => {
					//const typeArr = item.getArray<UTSJSONObject>("type") ?? [];
					//let typeObj : FMTypeConfigBean;
					//if (typeArr.length > 0) {
				//	let typeItem = typeArr[0] as UTSJSONObject;
					// typeObj = {
					// 	_id: typeItem.getString("_id") ?? "",
					// 	billType: typeItem.getString("billType") ?? "",
					// 	name: typeItem.getString("name") ?? "",
					// 	text: typeItem.getString("text") ?? "",
					// }
					FMList.push({
						_id: item.getString("_id") ?? "",
						amount: item.getNumber("amount") ?? 0,
						billType: item.getString("billType") ?? "",
						createTime: item.getNumber("createTime") ?? 0,
						creater: item.getString("creater") ?? "",
						//data_status: item.getNumber("data_status") ?? 0,
						hotel_id: item.getString("hotel_id") ?? "",
						ioeTime: item.getNumber("ioeTime") ?? 0,
						mark: item.getString("mark") ?? "",
						type: item.getString("type") ?? "",
						unit: item.getString("unit") ?? ""
					})
					//}

				})

			}
			let fMDataListResult : FMDataListResult = {
				count: res['count'] as number,//总数量
				pageNo: pageNo ?? 1,//当前页码
				pageSize: pageSize ?? 20,//每页数量
				fmList: FMList
			}
			return fMDataListResult;
		} catch (e) {
			console.error(e);
			throw new Error("获取收支列表失败");
		}


	}

	//房费统计按店铺分类
	getRoomOrder(hotel_id : string, st : number, et : number) {
		const db = dbJQL;
		const s1 = `hotel_id=='${hotel_id}'&&orderStatus==5`;
		const s2 = `checkInStartDateTimeStamp>=${st}&&checkInStartDateTimeStamp<${et}`;
		let w = `${s1}&&${s2}`;

		return db.collection("hm-order").where(w).groupBy('hotel_id').groupField('sum(totalAmount) as amount').get()
	}
	//房费统计月分组统计
	getRoomOrderOrderByMonth(hotel_id : string, st : number, et : number) {
		const db = dbJQL;
		const s1 = `hotel_id=='${hotel_id}'&&orderStatus==5`;
		const s2 = `checkInStartDateTimeStamp>=${st}&&checkInStartDateTimeStamp<${et}`;
		let w = `${s1}&&${s2}`;

		return db.collection("hm-order").where(w).groupBy('dateToString(timestampToDate(checkInStartDateTimeStamp),"%Y-%m") as month').groupField('sum(totalAmount) as amount').get()
	}
	//获取收入与支出分类
	async getIncomeAndExpenses(hotel_id : string, billType : string = 'income', st : number, et : number) {
		const db = dbJQL;
		const dbCmd = db.command;
		const w = {
			hotel_id: hotel_id,
			billType: billType,
			ioeTime: dbCmd.and([dbCmd.gte(st), dbCmd.lte(et)])
		}
		try {
			const res = await db.collection("hm-incomeAndExpenses").where(w).groupBy(' type as name').groupField('sum(amount) as value').get();
			return res;
		} catch (e) { }


	}
	//按月统计
	getIncomeAndExpensesByMonth(hotel_id : string, billType : string = 'income', st : number, et : number) {
		const db = dbJQL;
		const dbCmd = db.command;
		const w = {
			hotel_id: hotel_id,
			billType: billType,
			ioeTime: dbCmd.and([dbCmd.gte(st), dbCmd.lte(et)])
		}
		const res = db.collection("hm-incomeAndExpenses").where(w).groupBy(' dateToString(timestampToDate(ioeTime),"%Y-%m-%d") as month').groupField('sum(amount) as value').get();
		return res
	}

	//获取当月收入统计
	async getIncomeCurrentMonth(hotel_id : string, month : string) : Promise<Array<charPietItem>> {
		try {
		const db = dbJQL;
		const dbCmd = db.command;
		const monthFirst = getMonthFirstDay(month);
		const monthLast = getMonthLastDay(month);
		const w = {
			hotel_id: hotel_id,
			billType: 'income',
			ioeTime: dbCmd.and([dbCmd.gte(monthFirst), dbCmd.lte(monthLast)])
		}
		//房费
		const order = this.getRoomOrder(hotel_id, monthFirst, monthLast);
		const mt = db.collection("hm-incomeAndExpenses").where(w).get();
		const other = db.collection("hm-incomeAndExpenses", "hm-incomeAndExpensesConfig").where(w).groupBy('type').groupField('sum(amount) as value').get()
		let arr : Array<charPietItem> = [];
		const [orderRes, otherRes] = await Promise.all([order, other]);
		const orderList = orderRes["data"] as Array<UTSJSONObject> ?? [];
		const otherList = otherRes["data"] as Array<UTSJSONObject> ?? [];
		otherList.forEach(item => {
			const typeArray = item.getArray<UTSJSONObject>("type") ?? [];
			if (typeArray.length < 1) {
				return;
			}
			const typeObj = typeArray[0]
			const name = typeObj?.getString("text") ?? "--";
			const value = item.getNumber("value") ?? 0;
			arr.push({ name: name, value: value })
		})
		if (orderList.length > 0) {
			const first = orderList[0]
			const val = first.getNumber("amount") ?? 0
			const its : charPietItem = { name: "订单费用", value: val }
			arr.push(its)
		}

		return arr;
		}catch(error:Error){
			throw new Error(error.message)
		}
	}


	//获取当月支出统计
	async getExpensesCurrentMonth(hotel_id : string, month : string) : Promise<Array<charPietItem>> {
		try {
			
		
		const db = dbJQL;
		const dbCmd = db.command;
		const monthFirst = getMonthFirstDay(month);
		const monthLast = getMonthLastDay(month);
		const w = {
			hotel_id: hotel_id,
			billType: 'expenses',
			ioeTime: dbCmd.and([dbCmd.gte(monthFirst), dbCmd.lte(monthLast)])
		}
		const res = await db.collection("hm-incomeAndExpenses", "hm-incomeAndExpensesConfig").where(w).groupBy('type').groupField('sum(amount) as value').get()
		const expensesList = res["data"] as Array<UTSJSONObject> ?? [];
		let arr : Array<charPietItem> = [];
		expensesList.forEach(item => {
			const typeArray = item.getArray<UTSJSONObject>("type") ?? [];
			if (typeArray.length < 1) {
				return;
			}
			const typeObj = typeArray[0]
			const name = typeObj?.getString("text") ?? "--";
			const value = item.getNumber("value") ?? 0;
			arr.push({ name: name, value: value })
		})

		return arr;
		} catch (error:Error) {
			throw new Error(error.message)
		}
	}
	//获取当年收支统计
	/**
	 * year:年份
	 */
	async getIncomeAndExpensesCurrentYear(hotel_id : string, year : string, billType : string):Promise<Array<Array<number | string>>> {
		
		try {
			
		
		const db = dbJQL;
		const dbCmd = db.command;
		const yearFirst = new Date(new Date(year).getFullYear(), 0, 1).getTime();
		const yearLast = new Date(new Date(year).getFullYear(), 12, 1).getTime() - 1;
		const w = {
			hotel_id: hotel_id,
			billType: billType,
			ioeTime: dbCmd.and([dbCmd.gte(yearFirst), dbCmd.lte(yearLast)])
		}
		//房费
		const order = this.getRoomOrderOrderByMonth(hotel_id, yearFirst, yearLast);
		const other = db.collection("hm-incomeAndExpenses", "hm-incomeAndExpensesConfig").where(w).groupBy('dateToString(timestampToDate(ioeTime),"%Y-%m") as month').groupField('sum(amount) as amount').get();
		const [orderRes, otherRes] = await Promise.all([order, other]);
		const orderList = orderRes["data"] as Array<UTSJSONObject> ?? [];
		const otherList = otherRes["data"] as Array<UTSJSONObject> ?? [];
		let resultList : Array<Array<number | string>> = [];
		for (let i = 0; i < 12; i++) {
			const label = dayuts(new Date(new Date(year).getFullYear(), i)).format("YYYY-MM");
			const order = orderList.find(item => item.getString("month") == label);
			const other = otherList.find(item => item.getString("month") == label);
			let count = 0;
			if (order != null) {
				count += order.getNumber("amount") ?? 0;
			}
			if (other != null) {
				count += other.getNumber("amount") ?? 0;
			}
			resultList.push([label, count])
		}
		return resultList;
		} catch (error:Error) {
			throw new Error(error.message)
		}
	}


}


//module.exports =new AccountService();
export var FMService = new FMServiceClass();