import { DB } from '../api/DB';
import { callFunctionRes } from "@/bean/DBBean";
import { hotelBean } from '../bean/hotelBean';
import { roomTypeBean, formatRoomTypeList } from "@/bean/roomTypeBean.uts";
import { employeeBean } from '@/bean/employeeBean';
import { state } from '@/store/store.uts';
import {facilityConfig_type} from "@/bean/facilityConfig_type.uts";
import { showDialog, hideDialog } from "@/uni_modules/rice-ui";
import { ActionService } from './ActionService';

class HotelServiceClass {
	constructor() {}

	async updateDateBase() {}

	async getConfig_facilityConfig(type : string) : Promise<Array<facilityConfig_type>> {
		let params:string | UTSJSONObject = { type: type };
		if(type == 'all') {
			params = "";
		}
		const res = await DB.getCollection("hm-facilityConfig", params);
		const data = res['data'] as Array<UTSJSONObject>;
		let list:Array<facilityConfig_type> = [];
		data.forEach(item => {
			const fc:facilityConfig_type = {
				_id: item.getString("_id") ?? "",
				icon: item.getString("icon") ?? "",
				name: item.getString("name") ?? "",
				type: item.getString("type") ?? ""
			}
			list.push(fc)
		})
		return list;
	}

	async getOpendbCityChina(type : number) : Promise<Array<UTSJSONObject>> {
		const db = uniCloud.databaseForJQL();
		const res = await db.collection("opendb-city-china").where({ type }).get();
		const data = res['data'] as Array<UTSJSONObject>;
		return data;
	}

	async createHotel(hotelObj : hotelBean) : Promise<boolean> {
		try {
			const res = await ActionService.hotel_createHotel(hotelObj);
			const result = res["result"] as UTSJSONObject;
			const code = result.getNumber("code") ?? 0;
			const message = result.getString("message") ?? "";
			if (code != 0) {
				console.log("code error", code);
				uni.showToast({
					title: message,
					icon: "none"
				});
				throw new Error(message);
			}
			return true;
		} catch (e) {
			throw new Error("创建失败");
		}
	}

	async updateHotel(hotel_id : string, hotelObj : hotelBean) : Promise<boolean> {
		console.log("UPDATE+++++===", hotelObj);
		try {
			const res = await ActionService.hotel_updateHotel(hotel_id, hotelObj);
			console.log("update hotel", res);
			const result = res['result'] as UTSJSONObject;
			const code = result.getNumber("code") ?? 0;
			const message = result.getString("message") ?? "";
			if (code != 0) {
				console.log("code error", code);
				uni.showToast({
					title: message,
					icon: "none"
				});
				throw new Error(message);
			}
			uni.showToast({
				title: "更新成功",
				icon: "none"
			});
			return true;
		} catch (e) {
			throw new Error("更新失败");
		}
	}

	async deleteHotel(hotel_id : string) : Promise<boolean> {
		try {
			const res = await ActionService.hotel_deleteHotel(hotel_id);
			const result = res['result'] as UTSJSONObject;
			const code = result.getNumber("code") ?? 0;
			const message = result.getString("message") ?? "";
			if (code != 0) {
				console.log("code error", code);
				uni.showToast({
					title: message,
					icon: "none"
				});
				throw new Error(message);
			}			
			return true;
		} catch (error) {
			throw new Error("删除失败");
		}
	}

	async getHotelList() : Promise<Array<hotelBean>> {
		const res = await ActionService.hotel_getHotelList_x();
		const result = res.result as UTSJSONObject;
		const data = result.get('data') as Array<UTSJSONObject>;
		let hotelList:Array<hotelBean> = [];
		data.forEach(item => {
			const hotel:hotelBean = {
				_id: item.getString("_id") ?? "",
				ownership_id: item.getString("ownership_id") ?? "",
				belong: item.getString("belong") ?? "",
				hotelCoordinate: item.getArray<number>("hotelCoordinate") ?? [],
				hotelIntroduction: item.getString("hotelIntroduction") ?? "",
				hotelName: item.getString("hotelName") ?? "",
				firstImages: item.getString("firstImages") ?? "",
				imagesList: item.getArray<string>("imagesList") ?? [],
				athleticFacility: item.getArray<string>("athleticFacility") ?? [],
				cateringServices: item.getArray<string>("cateringServices") ?? [],
				recreationFacility: item.getArray<string>("recreationFacility") ?? [],
				feature: item.getArray<string>("feature") ?? [],
				serviceTel: item.getString("serviceTel") ?? "",
				wechat: item.getString("wechat") ?? "",
				hotelAddress: item.getString("hotelAddress") ?? "",
				hotelAddressArea: item.getString("hotelAddressArea") ?? "",
				hotelAddressCode: item.getString("hotelAddressCode") ?? "",
				baseFacility: item.getArray<string>("baseFacility") ?? [],
				curRole: item.getString("curRole") ?? ""
			}
			hotelList.push(hotel)
		})
		return hotelList;
	}

	getHotelListOfUser(phone : string) : Promise<UniCloudDBGetResult> {
		return DB.getCollection("hm-hotel", { belong: phone })
	}

	async getHotelInfoById(hotel_id : string): Promise<hotelBean> {
		try {
			const res = await DB.getCollection("hm-hotel", { _id: hotel_id } as UTSJSONObject);
			console.log("hotel::", res)
			const data = res['data'] as Array<UTSJSONObject>;
			const item = data[0] as UTSJSONObject;
			const hotel:hotelBean = {
				_id: item.getString("_id") ?? "",
				ownership_id: item.getString("ownership_id") ?? "",
				belong: item.getString("belong") ?? "",
				hotelCoordinate: item.getArray<number>("hotelCoordinate") ?? [],
				hotelIntroduction: item.getString("hotelIntroduction") ?? "",
				hotelName: item.getString("hotelName") ?? "",
				firstImages: item.getString("firstImages") ?? "",
				imagesList: item.getArray<string>("imagesList") ?? [],
				athleticFacility: item.getArray<string>("athleticFacility") ?? [],
				cateringServices: item.getArray<string>("cateringServices") ?? [],
				recreationFacility: item.getArray<string>("recreationFacility") ?? [],
				feature: item.getArray<string>("feature") ?? [],
				serviceTel: item.getString("serviceTel") ?? "",
				wechat: item.getString("wechat") ?? "",
				hotelAddress: item.getString("hotelAddress") ?? "",
				hotelAddressArea: item.getString("hotelAddressArea") ?? "",
				hotelAddressCode: item.getString("hotelAddressCode") ?? "",
				baseFacility: item.getArray<string>("baseFacility") ?? [],
				curRole: item.getString("curRole") ?? ""
			}
			return hotel;
		} catch(e) {
			throw new Error("获取酒店信息失败")
		}
	}

	async getEmployeeList(hotel_id : string) : Promise<employeeBean[]> {
		try {
			const where_ = { "hotel_id": hotel_id } as UTSJSONObject;
			const res = await DB.getCollectionOrderBy("hm-employee", where_, "role asc");
			console.log("getEmployeeList", res);
			const data = res["data"] as UTSJSONObject[];
			let list : Array<employeeBean> = [];

			data.forEach(item => {
				if (item != null) {
					const obj : employeeBean = {
						_id: item.getString("_id") ?? "",
						hotel_id: item.getString("hotel_id") ?? "",
						phone: item.getString("phone") ?? "",
						account: item.getString("account") ?? "",
						account_id: item.getString("account_id") ?? "",
						role: item.getString("role") ?? "",
						employee_name: item.getString("employee_name") ?? "",
						working_status: item.getNumber("working_status"),
						data_status: item.getNumber("data_status"),
						mark: item.getString("mark") ?? "",
					}
					list.push(obj)
				}
			})
			return list;
		} catch (e) {
			console.error(e);
			throw new Error("get employeeList fail");
		}
	}

	async deleteEmployee(_id : string) : Promise<boolean> {
		try {
			await ActionService.employee_deleteEmployee(_id);
			console.log("res", res);
			return true;
		} catch (error) {
			throw new Error("删除员工失败");
		}
	}

	async addEmployee(employeeForm : employeeBean) : Promise<boolean> {
		try {
			const { employee_name, hotel_id, account, phone, role, mark } = employeeForm;			
			const res = await ActionService.employee_addEmployee({ employee_name, hotel_id, phone, account, role, mark });
			console.log("eeeee", res);
			
			const result = res['result'] as UTSJSONObject;
			if(result.getNumber("errCode") != 0) {
				throw new Error(result.getString("errMsg") ?? "系统异常");
			}		
			return true;
		} catch (err) {
			showDialog({
				title: '添加失败',
				message: err.message.toString(),
				showCancelButton: false,
				confirm: () => {
					throw new Error(err.message.toString());
				}
			})
		}
	}

	async editEmployee(employeeForm : employeeBean): Promise<boolean> {
		try {
			const { _id, employee_name, hotel_id, account, phone, role, mark } = employeeForm;
			const res = await ActionService.employee_editEmployee(_id, { employee_name, hotel_id, account, phone, role, mark });
			const result = res['result'] as UTSJSONObject;
			const code = result.getNumber("code") ?? 0;
			const message = result.getString("message") ?? "";
			if (code != 0) {
				uni.showToast({
					title: message,
					icon: "none"
				});
				throw new Error(message);
			}
			uni.showToast({
				title: "更新成功",
				icon: "none"
			});
			return true;
		} catch (error) {
			console.log(error)
			throw new Error(error.message.toString());
		}
	}
}

export var HotelService = new HotelServiceClass();