import { linenWashingType, linenDataListResult } from '@/bean/linenWashingBean.uts';

import { action_co, RequestFailModal } from "@/api/cloudApi.uts";
type remainRoomBean = {
	_id : string
	room_name : string
}

import { DB, dbJQL } from '@/api/DB';
import { dayuts } from '@/uni_modules/lime-dayuts';
import { TIME, MOONTH_START_END_TIMESTAMP } from "@/static/utils/TIME";

class LinenOrderServiceClass {
	constructor() { }
	async addLinen(linen : linenWashingType) : Promise<boolean> {
		try {
			console.log(linen)
			const res = await action_co.linen_add(linen);
			return res['data'] as boolean;
		} catch (error : Error) {
			RequestFailModal(error.message);
			throw new Error(error.message as string)
		}

	}
	async editLinen(linen : linenWashingType) : Promise<boolean> {
		console.log("111111",linen)
		try {
			const res = await action_co.linen_edit(linen);
			return res['data'] as boolean;
		} catch (error : Error) {
			RequestFailModal(error.message);
			throw new Error(error.message as string)
		}

	}

	async getLinenListBySearch(hotel_id : string, dateRange : string[], status : string | number, pageNo : number, pageSize : number) : Promise<linenDataListResult> {
		let skipnum : number = Math.max((pageNo - 1) * pageSize, 0);
		const db = dbJQL;
		const dbCmd = db.command;
		let st : number = TIME.getCurrentMonthFirst(new Date());
		let et : number = TIME.getCurrentMonthLast(new Date());
		if (dateRange != null && dateRange.length == 2) {
			st = TIME.startTime(new Date(dateRange[0]));
			et = TIME.endTime(new Date(dateRange[1]));
		}
		console.log("wwww", st, et);
		const w = {
			hotel_id: hotel_id,
			createTime: dbCmd.and([dbCmd.gte(st), dbCmd.lte(et)]),
			status: status == 'all' ? dbCmd.neq(999) : status,
		}
		console.log("过滤条件", w);
		try {
			const res = await db.collection("hm-linen").where(w).orderBy("createTime desc").skip(skipnum).limit(pageSize).get({ getCount: true });
			console.log("order request", res)
			const data = res['data'] as Array<UTSJSONObject>;
			let linenList : Array<linenWashingType> = []
			if (data != null) {
				data.forEach((item : UTSJSONObject) => {
					 let linen: linenWashingType = {
					    _id: item.getString("_id") ?? "",
					    hotel_id: item.getString("hotel_id") ?? "",
					    createTime: item.getNumber("createTime") ?? 0,
					    returnBackTime: item.getNumber("returnBackTime") ?? 0,
					    service_provider: item.getString("service_provider") ?? "",
					    flatsheet_max_num: item.getNumber("flatsheet_max_num") ?? 0,
					    flatsheet_mini_num: item.getNumber("flatsheet_mini_num") ?? 0,
					    duvetCover_max_num: item.getNumber("duvetCover_max_num") ?? 0,
					    duvetCover_mini_num: item.getNumber("duvetCover_mini_num") ?? 0,
					    bathTowel_num: item.getNumber("bathTowel_num") ?? 0,
					    faceTowel_num: item.getNumber("faceTowel_num") ?? 0,
					    floorTowel_num: item.getNumber("floorTowel_num") ?? 0,
					    bedRunner_num: item.getNumber("bedRunner_num") ?? 0,
					    pillowcase_num: item.getNumber("pillowcase_num") ?? 0,
					    flatsheet_max_back_num: item.getNumber("flatsheet_max_back_num") ?? 0,
					    flatsheet_mini_back_num: item.getNumber("flatsheet_mini_back_num") ?? 0,
					    duvetCover_max_back_num: item.getNumber("duvetCover_max_back_num") ?? 0,
					    duvetCover_mini_back_num: item.getNumber("duvetCover_mini_back_num") ?? 0,
					    bathTowel_back_num: item.getNumber("bathTowel_back_num") ?? 0,
					    faceTowel_back_num: item.getNumber("faceTowel_back_num") ?? 0,
					    floorTowel_back_num: item.getNumber("floorTowel_back_num") ?? 0,
					    pillowcase_back_num: item.getNumber("pillowcase_back_num") ?? 0,
					    bedRunner_back_num: item.getNumber("bedRunner_back_num") ?? 0,
					    unit: item.getString("unit") ?? "",
					    status: item.getNumber("status") ?? 0,
					    mark: item.getString("mark") ?? ""
					  }
					linenList.push(linen);
				})
			}
			let linenResult : linenDataListResult = {
				count: res['count'] as number,
				pageNo: pageNo ?? 1,
				pageSize: pageSize ?? 20,
				linenList: linenList
			}
			return linenResult;
		} catch (error : Error) {
			console.log("eeeeee", error)
			throw new Error("获取订单列表失败")
		}



	}


	async lockLinen(_id : string) : Promise<Boolean> {
		try {
			const res = await action_co.linen_lock(_id);
			console.log("res", res)
			return res['data'] as boolean;
		} catch (error : Error) {
			RequestFailModal(error.message);
			throw new Error(error.message as string)
		}

	}
	async deleteLinen(_id : string) : Promise<Boolean> {
		try {
			const res = await action_co.linen_delete(_id);
			return res['data'] as boolean;
		} catch (error : Error) {
			RequestFailModal(error.message);
			throw new Error(error.message as string)
		}

	}
	updateLinen(_id : string, obj : UTSJSONObject) : Promise<UniCloudDBUpdateResult> {
		return DB.update("hm-order", _id, obj);
	}
}

export var LinenOrderService = new LinenOrderServiceClass();