import { orderSourceBean, orderBean, formatOrder, OrderRoomTypeBean, OrderDataListResult, remainRoomTypeBean } from '@/bean/orderBean';

type remainRoomBean = {
	_id : string
	room_name : string
}

import { DB } from '@/api/DB';
import { dayuts } from '@/uni_modules/lime-dayuts';
import { TIME, MOONTH_START_END_TIMESTAMP } from "@/static/utils/TIME";
import { roomTypeBean } from '../bean/roomTypeBean';
import { roomBean } from '../bean/roomBean';
import { ActionService } from './ActionService';

class OrderServiceClass {
	constructor() {}

	async getSource() : Promise<Array<orderSourceBean>> {
		let list : Array<orderSourceBean> = [];
		try {
			const res = await DB.getCollection("hm-orderSouce", {});
			let resultList = res['data'] as Array<UTSJSONObject>;
			resultList.forEach(item => {
				let os : orderSourceBean = {
					name: item.getString("name") ?? "",
					text: item.getString("text") ?? "",
					value: item.getNumber("value") ?? 0
				}
				list.push(os);
			})
			return list;
		} catch (error) {
			throw new Error("获取订单来源失败");
		}
	}

	async addOrder(orderObj : orderBean) : Promise<boolean> {
		const obj = {
			hotel_id: orderObj.hotel_id,
			userName: orderObj.userName,
			checkInStartDateTimeStamp: orderObj.checkInStartDateTimeStamp,
			checkInEndDateTimeStamp: orderObj.checkInEndDateTimeStamp,
			checkInStartDate: orderObj.checkInStartDate,
			checkInEndDate: orderObj.checkInEndDate,
			phone: orderObj.phone,
			createrPhone: orderObj.createrPhone,
			createrName: orderObj.userName,
			orderSource: orderObj.orderSource,
			orderSouce_Zn: orderObj.orderSouce_Zn,
			downPayment: orderObj.downPayment,
			totalAmount: orderObj.totalAmount,
			reservedRoomList: orderObj.reservedRoomList
		}
		try {
			const res = await ActionService.order_addOrder(obj);
			const result = res['result'] as UTSJSONObject;
			const code = result.getNumber("code") ?? 0;
			const message = result.getString("message") ?? "";
			if (code != 0) {
				uni.showToast({
					title: message,
					icon: "none"
				});
				throw new Error(message);
			}
			return true
		} catch (error) {
			throw new Error("创建失败");
		}
	}

	async deleteOrder(_id : string) : Promise<boolean> {
		try {
			await ActionService.order_deleteOrder(_id);
			console.log("删除订单")
			return true;
		} catch (error) {
			throw new Error("删除订单失败")
		}
	}

	updateOrder(_id : string, obj : UTSJSONObject) : Promise<UniCloudDBUpdateResult> {
		return DB.update("hm-order", _id, obj);
	}
}

export var OrderService = new OrderServiceClass();