import{DB,dbJQL} from '../api/DB';
import {callFunctionRes} from "@/bean/DBBean";
import {action_co,getTokenObject,RequestFailModal} from "@/api/cloudApi.uts";
class PermissionServiceClass{
    constructor(){
      
    }
    /*
    *获取角色列表
    */
    getRoleList():void{
    //     const db = uniCloud.database();
    //     const mt=   db.collection("hm-menuType").where({hotel_id}).getTemp();
    //     const mtd =  db.collection("hm-menuDetail").getTemp();
    //    return   db.collection(mt,mtd).get();
  
    }
    /*
    *获取用户角色
    */
    getUserRoleList(phone:string){

    }
     /*
    *获取权限列表
    */
    async getPermissionList(hotel_id:string):Promise<Array<string>>{
        //return DB.callFunction("hm_getPermission_x",{hotel_id});
		try {
			const res = await action_co.user_getPermission(hotel_id);
			console.log("permission list---",res)
			const data = res['data'] as Array<string>;
			return data;
		} catch (error:Error) {
			//TODO handle the exception
			RequestFailModal(error.message);
			throw new Error("get permission fail");
		}
		
    }
	/*
    *根据角色的权限列表
    */
 //   async getRolePermissionList(hotel_id:string):Promise<Array<string>>{  
 //         //return DB.callFunction("hm_getPermission",{hotel_id})  
	// 	 try{
	// 		  const res = action_co.user_getPermission(hotel_id);
	// 		  console.log("permission ===",res)
	// 		  const list = res['data'] as Array<string>;
	// 		  return list;
	// 	 }catch(error:Error){
	// 		 RequestFailModal(error.message);
	// 		 throw new Error(error.message)
	// 	 }
	
  
 //    }
    /*
    *获取用户权限列表
    */
    getUserPermissionList(phone: string){

    }
    //权限数组列表
    // formatPermissionToArray(list=[]){
    //     let arr =[];
    //     list.map(item=>{
    //       arr.push(item.permission_id[0].permission_name);  
    //     })
    //     return arr;
    // }
}
//module.exports =new PermissionService();
export var PermissionService=new PermissionServiceClass();