import { DB } from '../api/DB';
import { callFunctionRes } from "@/bean/DBBean";
import { ActionService } from './ActionService';

class PermissionServiceClass {
    constructor() {}

    getRoleList(): void {}

    getUserRoleList(phone: string) {}

    getPermissionList(hotel_id: string): Promise<UniCloudCallFunctionResult<UTSJSONObject>> {
        return ActionService.permission_getPermission_x(hotel_id);
    }

    getRolePermissionList(hotel_id: string): Promise<UniCloudCallFunctionResult<UTSJSONObject>> {  
        return ActionService.permission_getPermission(hotel_id);          
    }

    getUserPermissionList(phone: string) {}
}

export var PermissionService = new PermissionServiceClass();