import { DB } from '../api/DB';
import { callFunctionRes } from "@/bean/DBBean";
import { useCloudObject } from '@/utils/cloudObject';

const action_co = useCloudObject("hm_action_co") as { [key: string]: (...args: any[]) => Promise<UniCloudCallFunctionResult<UTSJSONObject>> };

class PermissionServiceClass {
    constructor() {}

    getRoleList(): void {}

    getUserRoleList(phone: string) {}

    getPermissionList(hotel_id: string): Promise<UniCloudCallFunctionResult<UTSJSONObject>> {
        return action_co['permission_getPermission_x']({ hotel_id });
    }

    getRolePermissionList(hotel_id: string): Promise<UniCloudCallFunctionResult<UTSJSONObject>> {  
        return action_co['permission_getPermission']({ hotel_id });          
    }

    getUserPermissionList(phone: string) {}
}

export var PermissionService = new PermissionServiceClass();