import { DB,dbJQL } from '../api/DB';
import { callFunctionRes } from "@/bean/DBBean";
import { hotelBean } from '../bean/hotelBean';
import { roomTypeBean, formatRoomTypeList } from "@/bean/roomTypeBean.uts";
import { employeeBean } from '@/bean/employeeBean';
import { state } from '@/store/store.uts';
import { roomBean } from '../bean/roomBean';
import {action_co ,getTokenObject,RequestFailModal} from "@/api/cloudApi.uts";
type employeeList_Res = {
	code : number;
	errCode : number;
	message : string;
	errMsg : string;
	systemInfo : any[];
	data : Array<employeeBean>;
}


class RoomTypeClass {
	constructor() {

	}

	/** 
	 * 获取当前酒店房型信息
	*/
	async getRoomTypeList(hotel_id : string) : Promise<Array<roomTypeBean>> {

		try {		
			const roomTypeTemp = dbJQL.collection('hm-roomType')
			  .where(`hotel_id == "${hotel_id}"`) .getTemp();		
			const roomTemp = dbJQL.collection('hm-room') .getTemp();
			const res = await dbJQL.collection(roomTypeTemp, roomTemp)
			  .get();
			const data = res['data'] as Array<UTSJSONObject>;
			let roomTypeList : Array<roomTypeBean> = formatRoomTypeList(data);
			return roomTypeList;
		} catch (error) {
			//TODO handle the exception
			throw new Error("获取房型数据失败");
		}

	}
	/**
	 * 根据房型id获取房间
	 * @param {*} room_type_id:
	 * @returns 
	 */
	getRoom(room_type_id : string) : Promise<UniCloudDBGetResult> {
		return DB.getCollection("hm-room", { _id: room_type_id })

	}
	/**
	 * 
	 * @param {*} hotel_id 
	 * @returns 根据店铺获取房间列表
	 */
	getRoomListByHotelId(hotel_id : string) : Promise<UniCloudDBGetResult> {
		return DB.getCollection("hm-room", { hotel_id: hotel_id });
	}
	/**
	 * 
	 * @param {*} hotel_id 
	 */
	async getRoomListByHotelIdGroupByRoomType(hotel_id : string) : Promise<UniCloudDBGetResult> {

		const db = dbJQL;
		const roomType = db.collection("hm-roomType").where({ hotel_id }).field("hotel_id,_id,name").getTemp();
		const res = await db.collection(roomType, "hm-room").where({ hotel_id }).get();
		return res;
	}

	/**
	 * 删除房型
	 * @param {*} data 
	 */
	// addRoomTypePrice(list){
	//   return DB.add("hm-roomTypePrice",list)
	// }
	async deleteRoomType(roomType_id : string) : Promise<boolean> {
		console.log("删除房型：：", roomType_id);

		try {
			 const res = await action_co.roomType_deleteRoomType(roomType_id);
			 console.log("delete room type",res)
			 const flag = res['data'] as boolean;
			 return flag;
		} catch (error:Error) {
			RequestFailModal(error.message)
			throw new Error("delete room type fail");
		}

	}
	async addRoomType(roomTypeForm : roomTypeBean) : Promise<boolean> {
		try {
			const {
				hotel_id,
				name,
				area,
				isWindow,
				guestNumber,
				firstImages,
				imagesList,
				bedList,
				roomList,
				facility,
				priceBase,
				independentBathroom } = roomTypeForm;
			const roomTypeObj = {
				hotel_id,
				name,
				area,
				isWindow,
				guestNumber,
				firstImages,
				imagesList,
				bedList,
				roomList,
				facility,
				priceBase,
				independentBathroom
			}
			const res = await action_co.roomType_addRoomType(roomTypeObj);
			const code = res['code'] as number;
			return code ==0;
		} catch (error:Error) {
			RequestFailModal(error.message);
			throw new Error("create room Type error");
		}

	}

	async updateRoomType(roomTypeForm : roomTypeBean) : Promise<boolean> {

		try {
			const {
				_id,
				hotel_id,
				name,
				area,
				isWindow,
				guestNumber,
				firstImages,
				imagesList,
				bedList,
				roomList,
				facility,
				priceBase,
				independentBathroom } = roomTypeForm;
			const roomTypeObj = {
				_id,
				hotel_id,
				name,
				area,
				isWindow,
				guestNumber,
				firstImages,
				imagesList,
				bedList,
				roomList,
				facility,
				priceBase,
				independentBathroom
			}
			const res = await action_co.roomType_updateRoomType(roomTypeObj);
			console.log("update room type",res);
			const code = res['code'] as number;
			return code ==0;
		} catch (error:Error) {
			RequestFailModal(error.message);
			throw new Error("更新失败");
		}
	}
	async addRoom(roomList : Array<roomBean>) : Promise<boolean> {
		try {
			let list : Array<UTSJSONObject> = [];
			roomList.forEach(item => {
				list.push({
					"hotel_id": item.hotel_id,
					"room_name": item.room_name,
					"room_type_id": item.room_type_id
				})
			});
			console.log("add",list);
			const res = await action_co.room_addRoom(list);
			console.log("add room",res);
			const code = res['code'] as number;
			const flag = code ==0?true:false;
			return flag;
		} catch (error) {
			throw new Error("添加房间失败");

		}
	}
	/**
	 * 修改房间
	 */
	async editRoom(room : roomBean) : Promise<boolean> {
		try {
			const roomObj={
				_id:room._id,
				//hotel_id: room.hotel_id,
				room_name: room.room_name,
				room_type_id: room.room_type_id
			}
			const res = await action_co.room_updateRoom(roomObj);
			const code = res['code'] as number;
			const flag = code == 0;
			return flag;
		} catch (error:Error) {
			throw new Error("修改房间失败");
	
		}
	}
	/**
	 * 删除房间
	 */
	async deleteRoom(room_id : string) : Promise<boolean> {
		try {
			try {
				 const res = await action_co.room_deleteRoom(room_id);
				 console.log("delete room",res)
				 const data = res['data'] as boolean;
				 console.log("data flag",data)
				 return data;
			} catch (error:Error) {
				console.log("error==",error)
				RequestFailModal(error.message)
				throw new Error("delete room type fail");
			}
		} catch (error) {
			throw new Error("删除房间失败");
		}

	}
}

//module.exports =new HotelService();
export var roomTypeService = new RoomTypeClass();
