export default {
	common: {
		loading: "加载中…",
		saving:"正在保存",
		noData: "没有{0}数据",
		system_error:"系统异常",
		totalCount: "共{0}条",
		modal_title:"提示",
		select_txt:"请选择",
		search_txt:"请输入关键字",
		btn_txt_search:"搜索",
		btn_txt_next: "下一步",
		btn_txt_create:"创建{0}",
		btn_txt_save:"保存",
		btn_txt_submit:"提交",
		btn_txt_delete:"删除",
		btn_txt_cancel:"取消",
		btn_txt_add:"新增{0}",
		btn_txt_modify:"修改",
		btn_txt_update:"更新",
		btn_txt_quick_Operation:"Quick Operation",
		add_success:"添加成功",
		add_fail:"添加失败",
		update_success:"更新成功",
		update_fail:"更新失败",
		delete_success:"删除成功",
		delete_fail:"删除失败",
		getData_success:"获取{0}数据成功",
		getData_fail:"获取{0}数据失败"
	},
	form: {
		valid_required: "必填项",
		valid_required_email: "邮箱不能为空",
		valid_required_phone: "手机号不能为空",
		valid_required_code: "验证码不能为空",
		valid_email: "邮箱格式不正确",
		valid_phone: "邮箱格式不正确",
		valid_code: "验证码格式不正确",
		pach_email: "请输入邮箱",
		pach_phone: "请输入手机号",
		pach_code: "请输入验证码",
		remark: "备注",
		pach_remark: "请输入备注内容",
		canendar_title:"请选择日期"
		

	},
	tab:{
			home: "首页",
			roomStatus: "房态",
			finance: "财务",
			function: "功能",
			mine: "我的"
		},
	permission: {
		noPermission: "没有足够的权限",
		contactAdmin: "请联系负责人",
	},
	indexAdvise: {
		title: "议宿 Yisu",
		subtitle: "专业酒店民宿智能管理工具",

		aboutUs: {
			title: "关于我们",
			content: "议宿是一款基于酒店民宿日常事务管理开发的工具类软件，提供基础的房型房间管理，收入与支出的财务管理，财务统计图表。订单与房态管理，并自动生成店铺个性化信息展示，并且能分享给其它用户，方便快速预览。酒店管理员随身管理类必备工具。",

		},
		coreFunction: {
			title: "核心功能",
			orderManage: "订单管理",
			orderManage_content: "订单管理，快速查看入住与退房",
			stateManage: "房态管理",
			stateManage_content: "一图看清入住数据",
			hotelRoomType: "房型管理",
			hotelRoomType_content: "酒店房型设施数据管理",
			financialManagement: "财务管理",
			financialManagement_content: "酒店收支管理与统计，一图看清营业状况",
			employeeAccount: "员工账号",
			employeeAccount_content: "提供员工子账号与员工数据管理",
			hotelDisplay: "酒店展示",
			hotelDisplay_content: "个性化展示与分享"
		},
		loginBtnTxt: "登录体验APP"


	},
	login: {
		title: "登录",
		tab_acount: "账号密码",
		tab_login_app: "一键登录",
		tab_login_sms: "短信验证",
		agreenTxt_one: "我已经同意",
		agreenTxt_two: "和",
		userAgreement: "《用户协议》",
		privacyPolicy: "《隐私政策》",
		regitser_txt: "还没有账号？立即注册",
		pach_account: "请输入账号名/邮箱/手机号",
		pach_password: "请输入密码",
		pach_phone: "请输入手机号",
		pach_sms: "请输入验证码",
		btn_txt_password: "忘记密码",
		btn_txt: "登录",
		btn_app_txt: "一键登录"，
		btn_getSms: "获取验证码",
		getphone_loading: "手机号获取中…",
		valid_required: "必填项",
		valid_agree: "请先同意用户协议与隐私政策",
		valid_password: "请完善账号密码",
		valid_password_num: "密码的长度不能小于6位",
		valid_password_comb: "密码需要包含字母和数字",
		valid_account: "请输入账户名",
		valid_account_num: "字数需为 3 至 25 位",
		valid_phone_num: "手机号长度为11位",
		valid_sms_num: "验证码为4位",
		valid_sms: "验证码为数字",
		send_sms_fail: "发送短信失败",
		login_success: "登录成功",
		pre_login_fail: "预登录失败",
		login_fail: "预登录失败",
		login_fail_content: "请用其它方式登录",
		valid_login_app_agree: "请先阅读并同意协议",
		login_regitser_success: "登录并注册成功",
		no_support_login_app: "当前环境暂不支持一键登录",
		tips_login_regitser: "该手机号未注册，将自动为您创建议宿账号",
		modal_title: "提示",
		tips: "未注册的手机号验证后自动创建议宿账号"
	},
	register: {
		title: "注册",
		register_account: "注册账号",
		pach_email: "请输入邮箱",
		pach_email_code: "请输入邮箱验证码",
		valid_email_hanused: "此邮箱已注册",
		valid_email_num: "邮箱验证码为 4 位",
		valid_password_again: "请再次输入密码",
		valid_account_require: "账号不能为空",
		valid_account_correct: "账号只能由字母数字组成",
		valid_account_hasused: "已存在相同用户名",
		valid_password_equal: "两次输入的密码不一致",
		email_tips: "* 如收不到邮箱验证码，请检查垃圾邮箱箱中是否存在",
		btn_txt: "下一步",
		btn_txt_complete: "完成注册",
		register_success: "注册成功"
	},
	hotel:{
		title:"酒店",
		hotel_list:"酒店列表",
		btn_txt_manage:"管理",
		current_hotel:"当前酒店",
		btn_txt_view_all:"查看全部",
		normal_operation: "正常营运"
		
		
		
	},
	setcontent:{
		btn_txt_sys_set:"系统设置",
		btn_txt_feedback:"意见反馈"
	},
	gather:{		
		    today: '今日',
		    tomorrow: '明日',
		    todayText: '今天',
		    tomorrowText: '明天',
		    checkInToday: '今日入住',
		    checkOutToday: '今日退房',
		    currentGuests: '当前在住',
		    emptyRooms: '空房数量',
		    checkInTomorrow: '明日入住',
		    checkOutTomorrow: '明日退房'
		  
	},
	order: {
		title_order:"订单",
		title: "房态",
		orderManage: "订单管理",
		room: "房间",
		date: "日期",
		remain: "剩余",
		noData: "没有数据",
		noRoom: "没有房间",
		weekSun: "周日",
		weekMon: "周一",
		weekTue: "周二",
		weekWed: "周三",
		weekThu: "周四",
		weekFri: "周五",
		weekSat: "周六",
		orderList: "订单列表",
		addOrder: "添加订单",

		// 筛选
		orderFilter: "订单筛选",
		searchPlaceholder: "搜索收入名称",
		remain_room:"剩余房间",
		// 订单状态
		statusAll: "全部",
		statusCheckInPending: "待入住",
		statusCompleted: "已完成",
		statusCancelled: "已撤销",

		// 订单信息
		guest: "住客：",
		checkInTime: "入住时间：",
		checkOutTime: "退房时间：",
		room: "房间：",
		remark: "备注信息：",
		roomPrice: "房价：",

		// 权限/提示
		noPermission: "没有足够的权限",
		contactAdmin: "请联系负责人",
		confirmDeleteOrder: "确认删除此订单",
		deleteOrderTip: "删除后将无法恢复，确认删除吗？",

		// 按钮
		next: "下一步",
		completeRegister: "完成注册",
		registerSuccess: "注册成功"
		all_roomType:"全部房型",
		create_order:{
			    edit_order_info: '修改订单信息',
			    order_info: '订单信息',
			    select_room: '选择房间',
			
			    // 表单标签
			    source: '来源',
			    date: '日期',
			    room_type_room: '房型房间',
			    customer_name: '客户名',
			    contact_phone: '联系电话',
			    deposit: '定金',
			    total_price: '总价',
			    remark: '备注',			
			    // 表单占位符
			    please_enter_wechat: '请输入客服微信',
			    please_enter_phone: '请输入客服电话',
			    please_enter_remark: '请输入备注内容',			
			    // 提示语/Toast
			    get_order_source_fail: '获取订单来源失败',
			    add_success: '添加成功',
			    add_order_fail: '添加订单失败',	
				select_room_num:'共{0}间可订',
				has_select_room_num:'已选择{0}间房',
				btn_txt:"确认选择",
				no_room_select_tips:"当前日期房间已经订完，请确认房间数据"
		}
	},
	fm:{
		title_income_expense:"收支"
	},
	//功能页面
	function:{
		title_navbar:"功能",
		title_set:"酒店设置",
		title_fm:"财务",
		title_order:"订单",
		btn_txt_room_type:"房型管理",
		btn_txt_room:"房间管理",
		btn_txt_room_employee:"员工管理",
		btn_txt_room_hotel_show:"酒店展示",
		btn_txt_income_expense:"收支管理",
		btn_txt_order:"订单管理",
		btn_txt_create_order:"添加订单",
		btn_txt_fm_chart:"财务统计"
		
		
	}

};