	import { hotelBean } from "@/bean/hotelBean.uts";
	import i18n from '@/i18n/index.uts';
export const  validForm = (hotelForm:hotelBean):boolean=>{
	let msg ="";

	
	if(hotelForm.wechat==""){
		//msg="请填写客服微信";
		msg=i18n.global.t("hotel.form.valid_customer_service_weChat")
		
	}
	if(hotelForm.serviceTel==""){
		//msg="请填写客服电话";
		msg=i18n.global.t("hotel.form.valid_customer_serviceTel");
	
	}
	if(hotelForm.hotelAddressArea==""||hotelForm.hotelAddressArea==null ||hotelForm.hotelAddress==""){
		//msg="请选择填写地址";
		msg=i18n.global.t("hotel.form.valid_customer_hotelAddress");
	
	}
	if(hotelForm.hotelName==""){
		//msg="请填写酒店名称";
		msg=i18n.global.t("hotel.form.valid_customer_hotelName");
	
	}
	
	if(msg!=""){
		uni.showToast({
			title:msg,
			icon:"none"
		})
		return false;
	}
	return true;
}