export type FMTypeConfigBean ={
	_id:string,
	billType:string,
	name:string,
	text:string
	
}
export type FMBean={
	_id: string,
	amount: number,
	billType: string,
	createTime?: number,
	creater: string,
	//data_status?: number,
	hotel_id: string,
	ioeTime: number,
	mark: string,
	type:string,
	// type_name?:string,
	// type_text?:string,
	unit?: string
}

export type FMDataListResult={
	count:number,//总数量
	pageNo:number,//当前页码
	pageSize:number,//每页数量
	fmList:Array<FMBean>//列表
}