
export type linenWashingType={
		"_id": string,
		"hotel_id":string,
		"createTime"?:number ,
		"returnBackTime"?: number,
		"service_provider":string,
		"flatsheet_max_num":number,
		"flatsheet_mini_num":number ,
		"duvetCover_max_num":number ,
		"duvetCover_mini_num":number ,
		"bathTowel_num":number,
		"faceTowel_num":number,
		"floorTowel_num":number,
		"bedRunner_num":number,	
		"pillowcase_num":number,
		"flatsheet_max_back_num":number,
		"flatsheet_mini_back_num":number ,
		"duvetCover_max_back_num":number,
		"duvetCover_mini_back_num":number ,
		"pillowcase_back_num":number,
		"bathTowel_back_num":number ,
		"faceTowel_back_num":number ,
		"floorTowel_back_num":number,
		"bedRunner_back_num": number,
		"unit"?:string ,
		"status"?:number ,
		mark:string

}
export type linenDataListResult={
	count: number,
	pageNo: number,//当前页码
	pageSize: number,//每页数量
	linenList: Array<linenWashingType>//列表
}