
export type linenWashingType={
		"_id": string,
		"hotel_id":string,
		"createTime":number ,
		"returnBackTime"?: number,
		"flatsheet20_num":number,
		"flatsheet18_num":number ,
		"flatsheet15_num":number,
		"flatsheet13_num":number,
		"flatsheet12_num":number,
		"duvetCoverMax_num":number ,
		"duvetCoverMini_num":number ,
		"bathTowel_num":number,
		"faceTowel_num":number,
		"floorTowel_num":number,
		"bedRunner_num":number,				
		"flatsheet20_back_num":number,
		"flatsheet18_back_num":number ,
		"flatsheet15_back_num":number,
		"flatsheet13_back_num":number,
		"flatsheet12_back_num": number,
		"duvetCoverMax_back_num":number,
		"duvetCoverMini_back_num":number ,
		"bathTowel_back_num":number ,
		"faceTowel_back_num":number ,
		"floorTowel_back_num":number,
		"bedRunner_back_num": number,
		"unit"?:string ,
		"status":number ,
		mark:string

}
export type linenDataListResult={
	count: number,
	pageNo: number,//当前页码
	pageSize: number,//每页数量
	linenList: Array<linenWashingType>//列表
}